name: Hello, World
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hey World!!"
      - run: date
      - run: curl https://www.yahoo.com  > test.txt
      - run: wc -l test.txt

